###########  MakeFile.env  ##########
# Top level pattern, include by Makefile of child directory
# in which variable like TOPDIR, TARGET or LIB may be needed

CC=gcc
MAKE=make

AR=ar cr
RM = -rm -rf

CFLAGS+=-Wall

dirs:=$(shell find . -maxdepth 1 -type d)
dirs:=$(basename $(patsubst ./%,%,$(dirs)))
dirs:=$(filter-out $(exclude_dirs),$(dirs))
SUBDIRS := $(dirs)

SRCS=$(wildcard *.c)
OBJS=$(SRCS:%.c=%.o)
DEPENDS=$(SRCS:%.c=%.d)


all:$(TARGET)  $(LIB) subdirs

$(LIB):$(OBJS) 
	$(AR)  $@  $^
	cp $@ $(LIBPATH) 

subdirs:$(SUBDIRS)
	for dir in $(SUBDIRS);\
	do $(MAKE) -C $$dir all||exit 1;\
	done

$(TARGET):$(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS) -L$(LIBPATH)
	cp $@ $(EXEPATH)


$(OBJS):%.o:%.c
	$(CC) -c $< -o $@ $(CFLAGS) -I$(INCPATH)


-include $(DEPENDS)

$(DEPENDS):%.d:%.c
	set -e; rm -f $@; \
	$(CC) -MM $(CFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[:]*,\1.o $@:,g' < $@.$$$$ > $@; \
	rm $@.$$$$

clean:
	for dir in $(SUBDIRS);\
	do $(MAKE) -C $$dir clean||exit 1;\
	done
	$(RM) $(TARGET) $(LIB)  $(OBJS) $(DEPENDS)
